### ISSUE TITLE
Feature Request: Cloud-based save storage

### ISSUE THREAD

**Issue by jboulter11** [webrcade/webrcade#6]
I'd love to see cloud-based saves so I can play a game on one browser, save that save state to Dropbox or my NAS, then go to another device and continue playing that same save state.

To me, this is my must-have feature that's missing right now, besides support for N64 and Gamecube.

Additionally, thanks for making this work well with Dropbox!  I do work at Dropbox, and if you run into issues with Dropbox integrations, I may be able to find someone who could help (though, not me, I work on the iOS app :P), so feel free to reach out.

**Comment by raz0red** [comment]
Absolutely! Cloud saves are on the short list of things to be added next.

Great to hear about Dropbox, it is a great service. I will absolutely reach out if I run into any issues when adding the save support.

**Comment by XargonWan** [comment]
I would add the ability to turn on and off the auto save/load feature.

**Comment by msmith067** [comment]
This would be my number 1 request.  I’m having issues where my save isn’t keeping between sessions.  THis would definitely help.  Especially for those who may use multiple devices.

**Comment by PaulLuigi** [comment]
It would be reallllllll cool if it was possible to read/write these cloud save files so that I could resume my game from an old (offline) device on webrcade, or bring my save from webrcade elsewhere (such as a retro handheld).  It doesn't have to be a simple process, and it's fine if it's only supported using a computer as an intermediary.

For long RPGs we might put tens or even hundreds of hours into a single game, so being able to switch devices occasionally is really nice.  Let's say I'm going on a trip where I can't bring my ideal Webrcade setup.  Ideally I could download my Chrono Trigger save, put it on mini retro device, play it there for a week, then upload it back to webrcade.  That's a world I would love to live in =)

**Comment by raz0red** [comment]
This is now available on the staging server (0.0.5) release.

Currently, it is in-game saves that save to cloud. In a subsequent release I will add full save/load state support for the could.

https://play-staging.webrcade.com
https://editor-stating.webrcade.com

**Comment by RivermanPaul** [comment]
That's awesome!!  Is it totally automatic to upload/download cloud saves?  Do we need to do something differently to try 0.0.5?

**Comment by raz0red** [comment]
You need to go into settings (either in the player or editor, enabled cloud save support, and then link to your Dropbox account.

You will need to repeat this once for each device/browser that you wish to use cloud saves with.
